title: FAIR Facilities and Instruments
description: Enabling transparency, reproducibility, and equity through persistent identifiers
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
github:
  is_project_page: false